version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: trollblock_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
     - trollblock
  waitforrabbit:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq
    command: rabbitmq:5672
    networks:
     - trollblock
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: trollblock_node
    ports:
      - '80:8080'
    env_file: .env
    user: node
    volumes:
     - .:/home/node/app
    networks:
     - trollblock
    depends_on:
      - waitforrabbit
networks:
  trollblock:
    driver: "bridge"